language: r
cache: packages

os:
  - linux
  - osx

r:
  - bioc-devel
  - bioc-release

matrix:
  allow_failures:
    - r: bioc-devel

bioc_required: true

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(line_exclusions = "R/zzz.R")'
